//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque
    {
        public int ProdutoId { get; set; }
        public Nullable<int> FornecedorId { get; set; }
        public Nullable<System.DateTime> DataUltEntrada { get; set; }
        public Nullable<System.DateTime> DataUltSaida { get; set; }
        public Nullable<decimal> QtdeUltEntrada { get; set; }
        public Nullable<decimal> QtdeUltSaida { get; set; }
        public Nullable<decimal> EstoqueReservado { get; set; }
        public decimal EstoqueReal { get; set; }
        public decimal EstoqueDisponivel { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
