//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.EstoqueMovimentacao = new HashSet<EstoqueMovimentacao>();
            this.PedidoItem = new HashSet<PedidoItem>();
        }
    
        public int PedidoId { get; set; }
        public string Tipo { get; set; }
        public System.DateTime DataEmissao { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> FornecedorId { get; set; }
        public int UsuarioId { get; set; }
        public string NumeroNf { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public int StatusPedidoId { get; set; }
        public Nullable<int> NrParcelas { get; set; }
        public Nullable<System.DateTime> DataCancelamento { get; set; }
        public string NrOrcamentoFornecedor { get; set; }
        public Nullable<System.DateTime> ValidadeProposta { get; set; }
        public string Frete { get; set; }
        public Nullable<int> TransportadorId { get; set; }
        public Nullable<decimal> ValorFrete { get; set; }
        public bool IsCotacao { get; set; }
        public Nullable<System.DateTime> DataInicialPgto { get; set; }
        public string Observacao { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public Nullable<decimal> Acrescimo { get; set; }
        public string Lote { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstoqueMovimentacao> EstoqueMovimentacao { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual StatusPedido StatusPedido { get; set; }
        public virtual Transportador Transportador { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}
