//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoItem
    {
        public int PedidoItemId { get; set; }
        public int PedidoId { get; set; }
        public int ProdutoId { get; set; }
        public decimal Quantidade { get; set; }
        public Nullable<decimal> PerctDesconto { get; set; }
        public Nullable<decimal> PerctAcrescimo { get; set; }
        public Nullable<decimal> ValorDesconto { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<short> DiasPrevisaoEntrega { get; set; }
        public Nullable<System.DateTime> DataEntrega { get; set; }
        public string ObservacaoItem { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
